<div class="container">
<h1 style="padding-top: 20px;" >Agenda - Online</h1><br>
    <form action="/" method="GET">
        <div class="row" >
            <div class="col-4">
                <select name="specialty_id" id="specialty_id" class="form-select  mb-3" aria-label=".form-select-lg example">
                    <option value="0" selected>Escolha uma especialidade</option>
                        <?php 
                            foreach ($this->view->especialidades as $index => $value) { ?>
                            <option value="<?= $value['id'] ?>"> <?= $value['descricao'] ?> </option>
                        <?php } ?>
                </select>
            </div>
            <div class="col-4">
                <button type="submit" class="btn btn-primary">Pesquisar</button>
            </div>
        </div>
    </form>
</div>

<div class="container">
    <div class="row">
    <?php if($this->view->totais['total'] >0) { ?> 
        <h5> <?= $this->view->totais['total'] ?> <?= $this->view->totais['descricao'] ?>s encontrados</h5>
    <?php } ?>
        <?php 
            foreach ($this->view->profissionais as $index => $value) { ?>
                <div class="col-4">
                    <div class="card " >
                        <?php if($value['pic'] != '') {  ?>
                            <img src="img/<?= $value['pic'] ?>" class="card-img-top " alt="...">
                        <?php }else{ ?>
                            <img src="img/default.png" style="width: 80%;" class="card-img-top " alt="...">
                        <?php } ?>
                        <div class="card-body" >
                            <h5 class="card-title"><?= $value['name'] ?></h5>
                            <p class="card-text"><?= $value['descricao'] ?></p>
                            <a href="/agenda?professional_id=<?= $value['profId'] ?>" class="btn btn-primary">Agendar</a>
                        </div>
                    </div>
                </div>
        <?php } ?>
    </div>
</div>