<head>
    <title>Feegow - Agendar</title>
</head>

<!-- Métodos carregados do arquivo script.js -->
<body onload="getEspecialidade(), getSources()">
    <div class="container">
        <h1 style="padding-top: 20px; padding-bottom: 20px;" >
            Agenda - Online
        </h1>
        
        <form action="/" method="GET">
            <div class="row" >
                <div class="col-4">

                    <!-- informações vindas da requisição AJAX de especialidades -->
                    <select name="specialty_id" id="specialty_id" class="form-select  mb-3" aria-label=".form-select-lg example">
                        <option value="0" selected>Escolha uma especialidade</option>
                    </select>
                </div>
                <div class="col-4">
                    <input type="button" class="btn btn-primary" onclick="getProfissionais()" value='Pesquisar'></input>
                </div>
            </div>
        </form>
    </div>
    </div>

    <!-- informações vindas da requisição AJAX em filtro de profissionais -->
    <div class="container" id='container' >
        <h4 id='count'></h4>
        <div class="row" id='rowCard'></div>
    </div>
</body>