<head>
    <script src="src/script.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
    <title>Feegow - Agendar</title>
</head>
<!-- Métodos carregados do arquivo script.js -->
<body onload="agendar(), getSources()">
<div class="container">
<h1 style="padding-top: 15px;">Agenda - Solicitar Horários</h1><br>

<!-- informações vindas da requisição AJAX de profissionais 
    1. se utilizado para inserção via AJAX deve colocar action="/confirma".
    2. se utilisado para inserção direta no MySQL via PHP deve colocar action="/solicitar_agenda".
-->
<div class="container">
    <form class="row g-3" id="form" action="/confirma" method="POST">
        <div class="row">
            <div class="col-4">
                <div class="card">
                        <img src="img/default.png" id="prof_pic" class="card-img-top " alt="...">
                    <div class="card-body">
                        <h5 class="card-title" id="name_prof" ></h5>
                        <p class="card-text" id="specialty_name" ></p>
                        <a href="/" class="btn btn-primary">Troca Profissional</a>
                    </div>
                </div>
            </div>

            <div class="col-6">
            <h3>Preencha seus dados</h4><br>
                <div class="row" id="dados">
                    <div class="col-6">
                        <input type="text" name="name" class="form-control form-select-lg" id="name" placeholder="Nome Completo">
                    </div>
                    <div class="col-6">

                        <!-- informações vindas da requisição AJAX de source_id -->
                        <select type="select" name='source_id' id="source_id" class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
                            <option value='0' selected>Como Conheceu?</option>
                        </select>
                    </div>
                    <div class="col-6">
                        <input type="text" name="birthdate" class="form-control form-select-lg" id="birthdate" placeholder="Nascimento">
                    </div>
                    <div class="col-6">
                        <input type="text" name="cpf" class="form-control form-select-lg" id="cpf" placeholder="CPF">
                    </div>
                    <div class="col-6" style="padding-top: 15px;">
                        <button class="btn btn-primary" onclick="enviarForm('form')">Solicitar Horários</button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    </div>
 
</body>
</html>

